package api

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/lssolutions-ie/lss-management-server/internal/crypto"
	"github.com/lssolutions-ie/lss-management-server/internal/logx"
)

// HandleInstall serves a one-time install script with embedded credentials.
// The token in the URL is the only authentication — this endpoint is unauthenticated.
//
// Route: GET /api/v1/install/{token}
func (h *Handler) HandleInstall(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.NotFound(w, r)
		return
	}

	rlg := logx.FromContext(r.Context())

	// Extract token from URL: /api/v1/install/{token}
	token := strings.TrimPrefix(r.URL.Path, "/api/v1/install/")
	token = strings.TrimSpace(token)
	if token == "" {
		http.NotFound(w, r)
		return
	}

	// Hash the token to look it up
	hash := sha256.Sum256([]byte(token))
	tokenHash := hex.EncodeToString(hash[:])

	tok, err := h.DB.GetInstallTokenByHash(tokenHash)
	if err != nil {
		rlg.Error("install token lookup failed", "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
	if tok == nil {
		http.NotFound(w, r)
		return
	}

	// Already used?
	if tok.UsedAt != nil {
		http.Error(w,
			"This registration key has already been used. Each key is valid for one node only. Generate a new key from the dashboard.",
			http.StatusGone)
		return
	}

	// Expired?
	if tok.ExpiresAt.Before(time.Now()) {
		http.Error(w,
			"This registration key has expired. Generate a new key from the dashboard.",
			http.StatusGone)
		return
	}

	// Mark as used
	if err := h.DB.MarkInstallTokenUsed(tok.ID); err != nil {
		rlg.Error("mark install token used failed", "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Look up the node to get UID + PSK
	node, err := h.DB.GetNodeByID(tok.NodeID)
	if err != nil || node == nil {
		rlg.Error("install token node lookup failed", "node_id", tok.NodeID, "err", fmt.Sprintf("%v", err))
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Decrypt the PSK
	psk, err := crypto.DecryptPSK(node.PSKEncrypted, h.AppKey)
	if err != nil {
		rlg.Error("install token decrypt psk failed", "node_id", node.ID, "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Derive server URL from request
	// Always HTTPS — the server URL is embedded in the node's config and used
	// for heartbeats carrying encrypted PSK payloads. Never HTTP.
	serverURL := fmt.Sprintf("https://%s", r.Host)

	// Detect platform
	osParam := r.URL.Query().Get("os")

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")

	if osParam == "windows" {
		fmt.Fprintf(w, `# Auto-generated by LSS Management Server
# One-time registration for node: %s
$env:LSS_SERVER_URL = "%s"
$env:LSS_NODE_UID = "%s"
$env:LSS_PSK_KEY = "%s"

Write-Host "Downloading LSS Backup CLI installer..."
irm https://raw.githubusercontent.com/lssolutions-ie/lss-backup-cli/main/v2/install-cli.ps1 | iex

Write-Host ""
Write-Host "Node registered with management server."
Write-Host "  Server: $env:LSS_SERVER_URL"
Write-Host "  Node ID: $env:LSS_NODE_UID"
`, node.UID, serverURL, node.UID, psk)
	} else {
		fmt.Fprintf(w, `#!/bin/bash
set -euo pipefail

# Auto-generated by LSS Management Server
# One-time registration for node: %s
export LSS_SERVER_URL="%s"
export LSS_NODE_UID="%s"
export LSS_PSK_KEY="%s"

echo "Downloading LSS Backup CLI installer..."
curl -fsSL https://raw.githubusercontent.com/lssolutions-ie/lss-backup-cli/main/v2/install-cli.sh | bash

echo ""
echo "Node registered with management server."
echo "  Server: $LSS_SERVER_URL"
echo "  Node ID: $LSS_NODE_UID"
`, node.UID, serverURL, node.UID, psk)
	}

	rlg.Info("install token redeemed", "node_id", node.ID, "uid", node.UID, "os", osParam)
	_ = h.DB.InsertServerAuditLog(0, "system", r.RemoteAddr, "install_token_redeemed", "critical",
		"redeem", "node", fmt.Sprintf("%d", node.ID),
		"Install token redeemed for node "+node.UID+" — CLI credentials served",
		map[string]string{"uid": node.UID, "os": osParam})
}

// HandleRecover serves a one-time recovery script with embedded credentials.
// The token in the URL is the only authentication — this endpoint is unauthenticated.
// The script includes LSS_RECOVERY_MODE=true so the CLI restores from DR backup.
//
// Route: GET /api/v1/recover/{token}
func (h *Handler) HandleRecover(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.NotFound(w, r)
		return
	}

	rlg := logx.FromContext(r.Context())

	// Extract token from URL: /api/v1/recover/{token}
	token := strings.TrimPrefix(r.URL.Path, "/api/v1/recover/")
	token = strings.TrimSpace(token)
	if token == "" {
		http.NotFound(w, r)
		return
	}

	// Hash the token to look it up
	hash := sha256.Sum256([]byte(token))
	tokenHash := hex.EncodeToString(hash[:])

	tok, err := h.DB.GetInstallTokenByHash(tokenHash)
	if err != nil {
		rlg.Error("recovery token lookup failed", "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
	if tok == nil {
		http.NotFound(w, r)
		return
	}

	// Already used?
	if tok.UsedAt != nil {
		http.Error(w,
			"This recovery key has already been used. Each key is valid for one use only. Generate a new key from the dashboard.",
			http.StatusGone)
		return
	}

	// Expired?
	if tok.ExpiresAt.Before(time.Now()) {
		http.Error(w,
			"This recovery key has expired. Generate a new key from the dashboard.",
			http.StatusGone)
		return
	}

	// Mark as used
	if err := h.DB.MarkInstallTokenUsed(tok.ID); err != nil {
		rlg.Error("mark recovery token used failed", "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Look up the node to get UID + PSK
	node, err := h.DB.GetNodeByID(tok.NodeID)
	if err != nil || node == nil {
		rlg.Error("recovery token node lookup failed", "node_id", tok.NodeID, "err", fmt.Sprintf("%v", err))
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Decrypt the PSK
	psk, err := crypto.DecryptPSK(node.PSKEncrypted, h.AppKey)
	if err != nil {
		rlg.Error("recovery token decrypt psk failed", "node_id", node.ID, "err", err.Error())
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}

	// Always HTTPS
	serverURL := fmt.Sprintf("https://%s", r.Host)

	// Detect platform
	osParam := r.URL.Query().Get("os")

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")

	if osParam == "windows" {
		fmt.Fprintf(w, `# Auto-generated by LSS Management Server — NODE RECOVERY
# Recovering node: %s (%s)
$env:LSS_SERVER_URL = "%s"
$env:LSS_NODE_UID = "%s"
$env:LSS_PSK_KEY = "%s"
$env:LSS_RECOVERY_MODE = "true"

Write-Host "Recovering node %s..."
irm https://raw.githubusercontent.com/lssolutions-ie/lss-backup-cli/main/v2/install-cli.ps1 | iex

Write-Host ""
Write-Host "Node recovery complete."
Write-Host "  Server: $env:LSS_SERVER_URL"
Write-Host "  Node ID: $env:LSS_NODE_UID"
`, node.UID, node.Name, serverURL, node.UID, psk, node.UID)
	} else {
		fmt.Fprintf(w, `#!/bin/bash
set -euo pipefail

# Auto-generated by LSS Management Server — NODE RECOVERY
# Recovering node: %s (%s)
export LSS_SERVER_URL="%s"
export LSS_NODE_UID="%s"
export LSS_PSK_KEY="%s"
export LSS_RECOVERY_MODE="true"

echo "Recovering node %s..."
curl -fsSL https://raw.githubusercontent.com/lssolutions-ie/lss-backup-cli/main/v2/install-cli.sh | bash

echo ""
echo "Node recovery complete."
echo "  Server: $LSS_SERVER_URL"
echo "  Node ID: $LSS_NODE_UID"
`, node.UID, node.Name, serverURL, node.UID, psk, node.UID)
	}

	rlg.Info("recovery token redeemed", "node_id", node.ID, "uid", node.UID, "name", node.Name, "os", osParam)
	_ = h.DB.InsertServerAuditLog(0, "system", r.RemoteAddr, "recovery_token_redeemed", "critical",
		"redeem", "node", fmt.Sprintf("%d", node.ID),
		"CRITICAL: Recovery token redeemed for node "+node.UID+" ("+node.Name+") — disaster recovery credentials served",
		map[string]string{"uid": node.UID, "node_name": node.Name, "os": osParam})
}
